"""require an email address on every user

Revision ID: 36b2825c13a2
Revises: 0f2c7cc90c78
Create Date: 2026-09-02 16:29:20.331270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b2825c13a2'
down_revision: Union[str, None] = '0f2c7cc90c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Rows predating the rule have no address, and the column is unique, so one
    # shared placeholder would collide the moment there were two. The id makes
    # each distinct and traceable back to the account it stands for.
    #
    # example.com, not .invalid: RFC 2606 reserves both, but only the domain
    # survives validation. `EmailStr` rejects .invalid outright, which would
    # leave these rows unserialisable — every request listing them would fail.
    # Nothing is deliverable to example.com either, which is the point.
    op.execute(
        """
        UPDATE users
        SET email = 'user-' || id || '@example.com'
        WHERE email IS NULL
        """
    )
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
